Repository defenseunicorns/leapfrogai-api, pull requests merged in 2024-03, with the labels that each got.

#75 remove deprecated event decorator
  main.py
Labels: tech-debt

#83 Multiarchitecture Release
  .github/workflows/release.yaml
Labels: enhancement

#84 fix: variable naming in release workflow
  .github/workflows/release.yaml
Labels: bug
